@layout('layout')

@startblock('title')
    <img src="https://raw.githubusercontent.com/valkyrjaio/art/refs/heads/master/full-logo/orange/php.png" width="400" alt="Valkyrja">
@endblock

@startblock('content')
    <div class="links">
        <a href="http://www.valkyrja.io/documentation">Documentation</a>
        &middot;
        <a href="https://github.com/valkyrjaio/valkyrja-php">GitHub</a>
        &middot;
        <a href="https://github.com/valkyrjaio/valkyrja-php/issues">Issues</a>
    </div>
@endblock
