<?php
/**
 * @var TemplateContract $template
 */

use Valkyrja\View\Template\Contract\TemplateContract;

$template->setLayout('layout');
?>

<?php $template->startBlock('title'); ?>
<img src="https://raw.githubusercontent.com/valkyrjaio/art/refs/heads/master/full-logo/orange/php.png" width="400" alt="Valkyrja">
<?php $template->endBlock('title'); ?>

<?php $template->startBlock('content'); ?>
<div class="links">
    <a href="http://www.valkyrja.io/documentation">Documentation</a>
    &middot;
    <a href="https://github.com/valkyrjaio/valkyrja-php">GitHub</a>
    &middot;
    <a href="https://github.com/valkyrjaio/valkyrja-php/issues">Issues</a>
</div>
<?php $template->endBlock('content'); ?>
