name: Create a New Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version component to bump'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - rc

run-name: "Release ${{ inputs.bump }} bump on ${{ github.ref_name }}"

permissions:
  contents: write

jobs:
  release:
    uses: valkyrjaio/.github/.github/workflows/_create-release.yml@a05d561b0818440bcd533380e5adf994d5f5e8d5
    secrets: inherit
    with:
      bump: ${{ inputs.bump }}
